// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Ro Ngoc Vo",
            "url": "github.com/rovn208",
            "email": "ngocro208@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/follows/followers": {
            "get": {
                "description": "Get list follower",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "follows"
                ],
                "summary": "Get list follower",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "20",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "0",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.listFollowResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "follows"
                ],
                "summary": "Follow user",
                "parameters": [
                    {
                        "description": "123456789",
                        "name": "following_user_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"messsage\": \"follow user successfully\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    },
                    "500": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "follows"
                ],
                "summary": "Unfollow user",
                "parameters": [
                    {
                        "description": "123456789",
                        "name": "following_user_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"messsage\": \"unfollow user successfully\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    },
                    "500": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    }
                }
            }
        },
        "/api/v1/follows/following": {
            "get": {
                "description": "Get list following",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "follows"
                ],
                "summary": "Get list following",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "20",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "0",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.listFollowResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    }
                }
            }
        },
        "/api/v1/users": {
            "post": {
                "description": "Create new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Create new user",
                "parameters": [
                    {
                        "description": "Username",
                        "name": "username",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "minLength": 6,
                        "description": "SecretPassword",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Full Name",
                        "name": "full_name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Email@gmail.com",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.userResponse"
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    },
                    "500": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    }
                }
            }
        },
        "/api/v1/users/login": {
            "post": {
                "description": "Login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "operationId": "login",
                "parameters": [
                    {
                        "minLength": 6,
                        "description": "Username",
                        "name": "username",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "minLength": 6,
                        "description": "Password",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.loginResponse"
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    },
                    "404": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    },
                    "500": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    }
                }
            }
        },
        "/api/v1/users/me": {
            "get": {
                "description": "Get current user information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get current user information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.userResponse"
                        }
                    },
                    "404": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    },
                    "500": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    }
                }
            },
            "put": {
                "description": "Update user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Update user information",
                "parameters": [
                    {
                        "minLength": 6,
                        "description": "SecretPassword",
                        "name": "password",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Email@gmail.com",
                        "name": "email",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "FullName",
                        "name": "full_name",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Username",
                        "name": "username",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.userResponse"
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    },
                    "500": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    }
                }
            }
        },
        "/api/v1/users/{id}": {
            "get": {
                "description": "Get user by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get user by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.userResponse"
                        }
                    },
                    "404": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    },
                    "500": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    }
                }
            }
        },
        "/api/v1/videos": {
            "get": {
                "description": "Get list video",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "video"
                ],
                "summary": "Get list video",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.videoResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    }
                }
            },
            "post": {
                "description": "Create new video",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "video"
                ],
                "summary": "Create new video",
                "parameters": [
                    {
                        "minLength": 6,
                        "description": "Video title",
                        "name": "title",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "foldername/video.mp4",
                        "name": "stream_url",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Video description",
                        "name": "description",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "URL of the thumbnail image. ie. https://i.ytimg.com/vi/-uFQzcY7YHc/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLBdAOc5E4H_G09C5wqorhYRsUwQrQ",
                        "name": "thumbnail_url",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "123451",
                        "name": "created_by",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.videoResponse"
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    },
                    "500": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    }
                }
            }
        },
        "/api/v1/videos/upload": {
            "post": {
                "description": "Add video via form uploading",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "video"
                ],
                "summary": "Add video via form uploading",
                "parameters": [
                    {
                        "type": "file",
                        "description": "video file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "minLength": 6,
                        "type": "string",
                        "description": "Video title",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Video description",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "URL of the thumbnail image. ie. https://i.ytimg.com/vi/-uFQzcY7YHc/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLBdAOc5E4H_G09C5wqorhYRsUwQrQ",
                        "name": "thumbnail_url",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "created video successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    },
                    "500": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    }
                }
            }
        },
        "/api/v1/videos/youtube": {
            "post": {
                "description": "Add video via youtube video url",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "video"
                ],
                "summary": "Add video via youtube video url",
                "parameters": [
                    {
                        "description": "https://www.youtube.com/watch?v=-uFQzcY7YHc",
                        "name": "url",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "created video successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    },
                    "500": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    }
                }
            }
        },
        "/api/v1/videos/{id}": {
            "get": {
                "description": "Get video",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "video"
                ],
                "summary": "Get video",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "12345",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.videoResponse"
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    },
                    "500": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    }
                }
            },
            "put": {
                "description": "Update video",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "video"
                ],
                "summary": "Update video",
                "parameters": [
                    {
                        "minLength": 6,
                        "description": "Video title",
                        "name": "title",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "foldername/video.mp4",
                        "name": "stream_url",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Video description",
                        "name": "description",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "URL of the thumbnail image. ie. https://i.ytimg.com/vi/-uFQzcY7YHc/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG\u0026rs=AOn4CLBdAOc5E4H_G09C5wqorhYRsUwQrQ",
                        "name": "thumbnail_url",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.videoResponse"
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    },
                    "500": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    }
                }
            },
            "delete": {
                "description": "Delete video",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "video"
                ],
                "summary": "Delete video",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "12345",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "deleted video successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    },
                    "500": {
                        "description": "{\"error\": \"error message\"}",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "api.listFollowResponse": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "api.loginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "access_token_expired_at": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "refresh_token_expired_at": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/api.userResponse"
                }
            }
        },
        "api.userResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "api.videoResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "stream_url": {
                    "type": "string"
                },
                "thumbnail_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "ROSS API",
	Description:      "Streaming service YouTube alike",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
