// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	DeleteVideo(ctx context.Context, id int64) error
	FollowUser(ctx context.Context, arg FollowUserParams) (Follow, error)
	GetListFollower(ctx context.Context, arg GetListFollowerParams) ([]Follow, error)
	GetListFollowing(ctx context.Context, arg GetListFollowingParams) ([]Follow, error)
	GetListVideo(ctx context.Context, arg GetListVideoParams) ([]Video, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetVideo(ctx context.Context, id int64) (Video, error)
	UnfollowUser(ctx context.Context, arg UnfollowUserParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateVideo(ctx context.Context, arg UpdateVideoParams) (Video, error)
}

var _ Querier = (*Queries)(nil)
